services:
    postgres:
        image: postgres:17.4-alpine3.21
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-d", "simplebank"]
            interval: 10s
            timeout: 3s
            retries: 3
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=simplebank
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            - DB_SOURCE=postgresql://root:root@postgres:5432/simplebank?sslmode=disable